### ISSUE TITLE
yt_dlp.utils.DownloadError: ERROR: [youtube] uaECuDuiKpw: Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by jisa8438** [LISA-KOREA/YouTube-Video-Download-Bot#15]
yt_dlp.utils.DownloadError: ERROR: [youtube] uaECuDuiKpw: Sign in to confirm you’re not a bot

**Comment by LISA-KOREA** [comment]
https://github.com/yt-dlp/yt-dlp/issues/10128#issue-2340308709


Click

**Comment by jisa8438** [comment]
I have installed https://github.com/coletdjnz/yt-dlp-youtube-oauth2
Now I can download youtube video with yt-dlp
But still can‘t download with YouTube-Video-Download-Bot
This error message：yt_dlp.utils.DownloadError: ERROR: [youtube+oauth2] BqqgkNA4uQI: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by LISA-KOREA** [comment]
Add youtube cookie solve the error
